name: zilant_look
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  equatable: ^2.0.7
  floor: ^1.5.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_hooks: ^0.21.2
  flutter_svg: ^2.0.17
  get_it: ^8.0.3
  go_router: ^14.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.3.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  json_annotation: ^4.9.0
  material_design_icons_flutter: ^7.0.7296
  path_provider: ^2.1.5
  retrofit: ^4.4.2
  uuid: ^4.5.1
  visibility_detector: ^0.4.0+2

dev_dependencies:
  build_runner: ^2.4.15
  floor_generator: ^1.5.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.9.0
  retrofit_generator: ^9.1.9

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  fonts:
    - family: SFPro-Light
      fonts:
        - asset: assets/fonts/SFProText-Light.ttf
    - family: SFPro-Medium
      fonts:
        - asset: assets/fonts/SFProText-Medium.ttf
    - family: SFPro-SemiBold
      fonts:
        - asset: assets/fonts/SFProText-Semibold.ttf
    - family: SFPro-Bold
      fonts:
        - asset: assets/fonts/SFProText-Bold.ttf
